apiVersion: v2
appVersion: "v0.1.0"
dependencies:
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 7.3.9
- name: nm-vllm
  repository: https://helm.neuralmagic.com
  version: 0.1.2
- condition: nm-vllm-grafana-dashboards.enabled
  name: nm-vllm-grafana-dashboards
  version: 1.0.1
  repository: https://helm.neuralmagic.com
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.12.0
description: |
  A Helm chart for nm-vllm server deployment with production monitoring
  additions including prometheus and grafana.
name: nm-vllm-production-monitoring
type: application
version: 0.1.0
