apiVersion: v2
appVersion: "v0.1.0"
dependencies:
- name: nm-vllm
  repository: https://helm.neuralmagic.com
  version: 0.1.1
description: |
  A Helm chart for nm-vllm server deployment with production monitoring additions.
name: nm-vllm-production-monitoring
type: application
version: 0.0.1
