apiVersion: v2
appVersion: "v0.1.0"
dependencies:
- name: nm-vllm
  repository: https://helm.neuralmagic.com
  version: 0.1.1
- name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.12.0
description: |
  A Helm chart for nm-vllm server deployment with production monitoring
  additions including prometheus and grafana.
name: nm-vllm-production-monitoring
type: application
version: 0.0.1
