# -- (object) Configuration for the nm-vllm server deployment and service.
# @default -- --
nm-vllm:
  podAnnotations:
    prometheus.io/scrape: "true"
grafana:
  enabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
    datasources:
      enabled: true
      httpMethod: POST
      uid: prometheus
      ## URL of prometheus datasource
      ##
      url: http://nm-vllm-prometheus-server/
      label: grafana_datasource
      labelValue: "1"
