# -- (object) Configuration for the datasource connecting prometheus and grafana.
# @default -- --
datasource:

  # -- The HTTP method to use for the Grafana datasource
  httpMethod: POST

  # -- The interval with which Grafana should scrape the prometheus datasource
  scrapeInternal: 15s

  # -- The uid to use for the Grafana datasource
  uid: prometheus

  # -- The URL to use for the Grafana datasource
  url: http://nm-vllm-prometheus-server/

# -- (object) Configuration for the Grafana deployment
# @default -- --
grafana:

  # -- Allows for deployment of containers alongside the Grafana container
  # for purposes such as importing dashboards and datasources.
  # @default -- --
  sidecar:

    # -- Enables the automatic import and management of Grafana dashboards from ConfigMaps or secrets.
    # @default -- --
    dashboards:

      # -- Enable the Grafana sidecar for dashboards so nm-vllm dashboards can
      # be detected and loaded. If disabled, dashboards must be loaded manually.
      enabled: true

    # -- Enables the dynamic configuration of datasources from ConfigMaps or secrets.
    # @default -- --
    datasources:

      # -- Enable the Grafana sidecar for datasources so the prometheus
      # instance can be configured and used as a Grafana datasource. If disabled,
      # the prometheus datasource must be configured manually.
      enabled: true


# -- Label used by Grafana's sidecar for datasources to identify config
# maps with datasources that should be added to Grafana. Should match the value
# of the `sidecar.datasources.label` configuration in the Grafana chart.
grafanaDatasourcesLabelOverride: null


# -- Label value used by Grafana's sidecar for datasources to identify config
# maps with datasources that should be added to Grafana. Should match the value
# of the `sidecar.datasources.labelValue` configuration in the Grafana chart.
grafanaDatasourcesLabelValueOverride: null

# -- (object) Configuration for the nm-vllm server deployment and service.
# @default -- --
nm-vllm:
  podAnnotations:
      # -- Enables prometheus to find pod to scrape
    prometheus.io/scrape: "true"
