# -- (object) Configuration for the nm-vllm server deployment and service.
# @default -- --
nm-vllm:
  podAnnotations:
      # -- Enables prometheus to find pod to scrape.
    prometheus.io/scrape: "true"
# -- Namespace of values for Grafana
# @default -- --
grafana:

  # -- Allows for deployment of containers alongside the Grafana container
  # for purposes such as importing dashboards and datasources.
  # @default -- --
  sidecar:

    # -- Enables the automatic import and management of Grafana dashboards from ConfigMaps or secrets.
    # @default -- --
    dashboards:

      # -- True is required to enable sidecar dashboards.
      enabled: true

    # -- Enables the dynamic configuration of datasources from ConfigMaps or secrets.
    # @default -- --
    datasources:
      # -- True is required to enable sidecar datasources.
      enabled: true

      # -- Grafana sidecar datasource label.
      label: grafana_datasource

      # -- Grafana sidecar datasource label value.
      labelValue: ""

# -- Grafana datasource http method.
datasourceHttpMethod: POST

# -- Grafana datasource uid.
datasourceUid: prometheus

# -- Grafana datasource url.
datasourceUrl: http://nm-vllm-prometheus-server/
