# -- (object) Configuration for the nm-vllm server deployment and service.
# @default -- --
nm-vllm:
  podAnnotations:
    prometheus.io/scrape: "true"

grafana:
  enabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      annotations: {}
    datasources:
      enabled: true

      ## URL of prometheus datasource
      ##
      url: http://:9090/

      label: grafana_datasource
      labelValue: "1"
