# -- The HTTP method to use for the grafana datasource
datasourceHttpMethod: POST

# -- The uid to use for the grafana datasource
datasourceUid: prometheus

# -- The URL to use for the grafana datasource
datasourceUrl: http://nm-vllm-prometheus-server/

# -- (object) Configuration for the grafana deployment
# @default -- --
grafana:
  sidecar:
    dashboards:
      # -- Enable the grafana sidecar for dashboards so nm-vllm dashboards can
      # be detected and loaded. If disabled, dashboards must be loaded manually.
      enabled: true

    datasources:
      # -- Enable the grafana sidecar for datasources so the prometheus
      # instance can be configured and used as a grafana datasource. If disabled,
      # the prometheus datasource must be configured manually.
      enabled: true

      # -- Grafana sidecar datasource label
      label: grafana_datasource

      # -- Grafana sidecar datasource label
      labelValue: "1"

# -- (object) Configuration for the nm-vllm server deployment and service.
# @default -- --
nm-vllm:
  podAnnotations:
      # -- Enables prometheus to find pod to scrape
    prometheus.io/scrape: "true"
