apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nm-vllm.labels" . | nindent 4 }}
  name: {{ include "nm-vllm.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "nm-vllm.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
