affinity: {}
fullnameOverride: ""
image:
  repository: ghcr.io/neuralmagic/nm-vllm-openai
  pullPolicy: IfNotPresent
  tag: v0.1.0
modelName: mistralai/Mistral-7B-v0.1
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
replicaCount: 1
resources: {}
securityContext: {}
service:
  type: LoadBalancer
  port: 80
tolerations: []
volumeMounts: []
volumes: []
