# -- Provide affinity rules for the pod scheduling.
affinity: {}
# -- Provide a name to substitute for the full names of resources.
fullnameOverride: ""
image:
  # -- The Docker image repository for the application.
  repository: ghcr.io/neuralmagic/nm-vllm-openai
  # -- The pull policy for the Docker image.
  pullPolicy: IfNotPresent
  # -- The tag of the Docker image to use.
  tag: v0.1.0
modelName: mistralai/Mistral-7B-v0.1
# -- Provide a name to substitute for the name of the chart.
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
replicaCount: 1
resources: {}
securityContext: {}
service:
  type: LoadBalancer
  port: 80
tolerations: []
volumeMounts: []
volumes: []
