{{/*
  A lot of inspiration taken from:
    - https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nm-vllm-production-monitoring.fullname" . }}-grafana-datasource
  labels:
    {{ $.Values.grafana.sidecar.datasources.label }}: {{ $.Values.grafana.sidecar.datasources.labelValue | quote }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
{{- $scrapeInterval := .Values.scrapeInterval | default "15s" }}
    - name: Prometheus
      type: prometheus
      uid: {{ .Values.datasourceUid }}
      url: {{ .Values.datasourceUrl }}
      isDefault: true
      access: proxy
      jsonData:
        httpMethod: {{ .Values.datasourceHttpMethod }}
        timeInterval: {{ $scrapeInterval }}

# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
