{{- /*
  A lot of inspiration taken from:
    - https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
*/ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{ include "nm-vllm-production-monitoring.grafanaDatasourcesLabel" $ }}: {{ include "nm-vllm-production-monitoring.grafanaDatasourcesLabelValue" $ | quote}}
  name: {{ template "nm-vllm-production-monitoring.fullname" . }}-grafana-datasource
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: {{ .Values.datasource.isDefault }}
      jsonData:
        httpMethod: {{ .Values.datasource.httpMethod }}
        timeInterval: {{ .Values.datasource.timeInterval | default "15s" }}
      name: {{ .Values.datasource.name }}
      type: prometheus
      uid: {{ .Values.datasource.uid }}
      url: {{ .Values.datasource.url }}
