{{/*
  A lot of inspiration taken from:
    - https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nm-vllm-production-monitoring.fullname" . }}-grafana-datasource
  labels:
    {{ $.Values.grafanaDatasourcesLabel }}: {{ $.Values.grafanaDatasourcesLabelValue | quote }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      jsonData:
        httpMethod: {{ .Values.datasourceHttpMethod }}
        timeInterval: {{ .Values.scrapeInterval | default "15s" }}
      name: Prometheus
      type: prometheus
      uid: {{ .Values.datasourceUid }}
      url: {{ .Values.datasourceUrl }}
